vich_uploader:
  db_driver: orm

  mappings:
    plantes:
      uri_prefix: /images/plantes
      upload_destination: "%kernel.project_dir%/public/images/plantes"
      namer: Vich\UploaderBundle\Naming\UniqidNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
